[package]
name = "kiparse-rs"
version = "0.1.0"
authors = ["Elen Eisendle <ln@calcifer.ee>, Eugenio La Cava <fuzzywolf36@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

<<<<<<< HEAD
 [dependencies]
 lexpr = {version = "0.2.6", path = 'C:\Users\eugen\OneDrive\Documenti\programmazione\rust\lexpr-rs\lexpr'}
=======
[dependencies]
lexpr = { version = "0.2.6" }
>>>>>>> main/main

# [patch.crates-io]
# lexpr = { git = 'https://github.com/eugenio/lexpr-rs', branch = 'kicad_pcb-sexp' }
